/* tslint:disable */
/* eslint-disable */
/**
 * interview api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetUserToken200Response,
  GetUserTokenRequest,
} from '../models/index';

export interface GetUserTokenOperationRequest {
    getUserTokenRequest?: GetUserTokenRequest;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     * 生成登录token
     */
    async getUserTokenRaw(requestParameters: GetUserTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUserToken200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/user/send_mail`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getUserTokenRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 生成登录token
     */
    async getUserToken(requestParameters: GetUserTokenOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUserToken200Response> {
        const response = await this.getUserTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
